In [21]:
import numpy as np

In [54]:
paramMins = np.array([0, 0.5, 0.5])
paramMaxs = np.array([0.5, 1.2, 2.0])
div = 2
param_ranges = np.zeros((len(paramMins), div))
for qq in range(len(paramMins)):
    param_ranges[qq] = np.arange(paramMins[qq], paramMaxs[qq], (paramMaxs[qq] - paramMins[qq])/div)

meshes = np.meshgrid(*param_ranges, sparse=False, indexing='ij')

In [55]:
lists = [point for point in zip(*meshes)]
lists

[(array([[0., 0.],
         [0., 0.]]), array([[0.5 , 0.5 ],
         [0.85, 0.85]]), array([[0.5 , 1.25],
         [0.5 , 1.25]])), (array([[0.25, 0.25],
         [0.25, 0.25]]), array([[0.5 , 0.5 ],
         [0.85, 0.85]]), array([[0.5 , 1.25],
         [0.5 , 1.25]]))]

In [56]:
param1_range = np.arange(paramMins[0], paramMaxs[0], (paramMaxs[0] - paramMins[0]) / div)
param2_range = np.arange(paramMins[1], paramMaxs[1], (paramMaxs[1] - paramMins[1]) / div)
param3_range = np.arange(paramMins[2], paramMaxs[2], (paramMaxs[2] - paramMins[2]) / div)
param1_mesh, param2_mesh, param3_mesh = np.meshgrid(param1_range, param2_range, param3_range, sparse=False, indexing='ij')

In [57]:
list2 = [(param1, param2) for (param1, param2) in zip(param1_mesh, param2_mesh)]
list2

[(array([[0., 0.],
         [0., 0.]]), array([[0.5 , 0.5 ],
         [0.85, 0.85]])), (array([[0.25, 0.25],
         [0.25, 0.25]]), array([[0.5 , 0.5 ],
         [0.85, 0.85]]))]

In [58]:
for pointed in zip(*meshes):
    print(pointed)
    break;

(array([[0., 0.],
       [0., 0.]]), array([[0.5 , 0.5 ],
       [0.85, 0.85]]), array([[0.5 , 1.25],
       [0.5 , 1.25]]))


In [48]:
mm = np.meshgrid([1,2], [3, 4], [5,6], indexing='xy')
for x in zip(mm):
    print(x)

(array([[[1, 1],
        [2, 2]],

       [[1, 1],
        [2, 2]]]),)
(array([[[3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4]]]),)
(array([[[5, 6],
        [5, 6]],

       [[5, 6],
        [5, 6]]]),)
